name: Ookla Speedtest CLI
version: 1.0.0
slug: ookla-speedtest
description: Internet speed test sensor using the official speedtest.net CLI client
arch:
  - i386
  - amd64
  - armhf
  - aarch64
startup: application
image: "ghcr.io/caraar12345/home-assistant-addons/speedtest-mqtt"
boot: auto
icon: logo.png
logo: logo.png
hassio_api: true
apparmor: true
services:
  - mqtt:need
options:
  mqtt_topic: "homeassistant/speedtest"
  mqtt_options: ""
  cron: "0 * * * *"
schema:
  mqtt_topic: str
  mqtt_options: str?
  cron: str
