name: Ookla Speedtest CLI
version: 0.0.1
slug: ookla-speedtest
description: Internet speed test sensor using the official speedtest.net CLI client
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
icon: logo.png
logo: logo.png
apparmor: true
options:
  mqtt_host: null
  mqtt_port: 1883
  mqtt_id: "speedtest-cli-hass"
  mqtt_topic: "homeassistant/speedtest"
  mqtt_options: ""
  mqtt_username: ""
  mqtt_password: ""
  cron: "0 * * * *"
schema:
  mqtt_host: str
  mqtt_port: int(1, 65535)
  mqtt_id: str
  mqtt_topic: str
  mqtt_options: str?
  mqtt_username: str?
  mqtt_password: password?
  cron: str